=== manilouamerali/projet_catalogue/WebContent/CatalogueSchema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

<xs:element name="application">
	<xs:complexType>
	 <xs:sequence>
	  <xs:element name="catalogue" minOccurs="0" maxOccurs="1000">
	    <xs:complexType mixed="true">
	      <xs:sequence>
	      	<xs:element name="personne" minOccurs="1" maxOccurs="1">
				    <xs:complexType mixed="true">
	      				<xs:sequence>
	        				<xs:element type="xs:string" name="nomP" minOccurs='1' maxOccurs='1'/>
	        				<xs:element type="xs:string" name="prenomP" minOccurs='1' maxOccurs='1'/>
	  					</xs:sequence>
	  				</xs:complexType>
	  			</xs:element>
	        <xs:element type="xs:string" name="theme" minOccurs='1' maxOccurs='1'/>
	        <xs:element name="photo" minOccurs="0" maxOccurs="1000">
	          <xs:complexType mixed="true">
	            <xs:sequence>
	              <xs:element type="xs:anyURI" name="img"/>
	              <xs:element type="xs:date" name="dateAjout"/>
	              <xs:element type="xs:string" name="titre"/>
	              <xs:element type="xs:string" name="dimension"/> <!--  a vérifer -->
	              <xs:element type="xs:decimal" name="resolution"/>
	              <xs:element type="xs:string" name="categorie"/>
	              <xs:element type="xs:string" name="commentaire"/>
				  <xs:element type="xs:decimal" name="note"/>
				  <xs:element type="xs:decimal" name="sommeVotes"/>
				  <xs:element type="xs:decimal" name="nbVotes"/>
				  
				  <xs:element name="personne" minOccurs="1" maxOccurs="1">
				    <xs:complexType mixed="true">
	      				<xs:sequence>
	        				<xs:element type="xs:string" name="nomP" minOccurs='1' maxOccurs='1'/>
	        				<xs:element type="xs:string" name="prenomP" minOccurs='1' maxOccurs='4'/>
	        				<xs:element type="xs:decimal" name="idP" minOccurs='1' maxOccurs='1'/>
	        				<xs:element type="xs:string" name="email" minOccurs='1' maxOccurs='1'/>
	  					</xs:sequence>
	  				</xs:complexType>
	  			</xs:element>  	  
	            </xs:sequence>
	            <xs:attribute type="xs:date" name="datePrise"/>
	            <xs:attribute type="xs:string" name="lieu"/>
	        </xs:complexType>
	        </xs:element>
	      </xs:sequence>
	      <xs:attribute type="xs:date" name="dateCreation" use='required'/>
	    </xs:complexType>
	  </xs:element>
	 </xs:sequence>
	 <xs:attribute type="xs:string" name="nom"/>
	</xs:complexType>
  </xs:element>
</xs:schema>

=== manilouamerali/projet_catalogue/WebContent/Catalogue.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CatalogueSchema.xsd">
	<catalogue dateCreation="2015-10-01" theme="CatalogueManil">
		<personne>
			<nomP>tata</nomP>
			<prenomP>tutu</prenomP>
		</personne>
		
		<photo datePrise="2015-10-01" lieu="Bordeaux" titre="Tour_Eiffel.jpg">
			<commentaire>il faisait beau</commentaire>
			<personne>
				<nomP>tata</nomP>
				<prenomP>tutu</prenomP>
			</personne>
		</photo>
		
		<photo datePrise="2015-10-01" lieu="Bordeaux" titre="statuedelaliberte.jpg">
			<commentaire>il faisait beau</commentaire>
			<personne>
				<nomP>tata</nomP>
				<prenomP>tutu</prenomP>
			</personne>
		</photo>

</catalogue>

</application>
